### ISSUE TITLE
kotlin.UninitializedPropertyAccessException: lateinit property coroutineScope has not been initialized

### ISSUE THREAD

**Issue by gprtskh** [chyiiiiiiiiiiii/flutter_zendesk_messaging#10]
Hi @chyiiiiiiiiiiii, thanks for the plugin.
I have a problem on Android, when starting typing on Android, the app is crashed and returns this error: `kotlin.UninitializedPropertyAccessException: lateinit property coroutineScope has not been initialized`
Version: 2.6.0+1

**Comment by JimmyTai** [comment]
Please try version 2.9.3. If you encounter this issue again please re-open it.
