### ISSUE TITLE
How verify de zendeskmessagem is inicialized?

### ISSUE THREAD

**Issue by maurojohann** [chyiiiiiiiiiiii/flutter_zendesk_messaging#11]
I would like to check if there is already an instance started or if it is possible to close an instance.. I need to do this when changing user.

**Comment by VictorUvarov** [comment]
Why do you need to close an instance? The instance is initialized with the iOS or android channel key.

Does logging out/ in the new user work?

The plugin currently does nothing if Zendesk has been already initialized

**Comment by chyiiiiiiiiiiii** [comment]
@maurojohann Now, you can use isInitialized() in the new version.

**Comment by maurojohann** [comment]
Hi,
I needed the user to be able to logout of the app, and if another user signin, they would not enter the same session. But if I called the method `ZendeskMessaging.logoutUser()`, without `ZendeskMessaging.show` being called, an error was expected. But I solved it, creating a singleton class to make the control.

thanks a lot for the package.
