### ISSUE TITLE
MissingPluginException(No implementation found for method show on channel zendesk_messaging)}

### ISSUE THREAD

**Issue by Oladips** [chyiiiiiiiiiiii/flutter_zendesk_messaging#16]
ZendeskMessaging - show - Error: MissingPluginException(No implementation found for method show on channel zendesk_messaging)}

I get this error when i call ZendeskMessaging.show();

**Comment by DouglasValerio** [comment]
This error usually happens when you add a plugin that has some native implementation while running your app in debug mode.
This can be solved by killing your app and running it again, thus allowing for the native methods to be registered during the build process.

**Comment by gilsonjuniorpro** [comment]
Sorry but how can I do this? "allowing for the native methods to be registered during the build process"

**Comment by JimmyTai** [comment]
I will close the issue. If you meet this issue again please re-open or create a new issue. Thank u.
