### ISSUE TITLE
Problem in release Android

### ISSUE THREAD

**Issue by urielvexi** [chyiiiiiiiiiiii/flutter_zendesk_messaging#23]
this package used to work form me, since I updated to zendesk_messaging: ^2.7.5 now I get the next error in release:
`[ZendeskMessaging] - initialize failure - java.lang.AssertionError: Missing field in a9.b
[ZendeskMessagingPlugin] - Messaging needs to be initialized first`

it still works in debug, any idea how could I fix it?

**Comment by Pride049** [comment]
@urielvexi The same issue, release apk cannot do anything and without any log output.  Did you have any workaround for this? Thanks!

**Comment by urielvexi** [comment]
@Pride049 I did a downgrade to 2.7.4, I didn't find a workaround for 2.7.5

**Comment by Pride049** [comment]
Thanks, it looks good on 2.7.4.

**Comment by xang555** [comment]
if you using proguard add this line

```
# Zendesk
-keepnames class zendesk.** { *; }
```

**Comment by manalisangani18** [comment]
**Add these code in project level build.gradle**

```
repositories {
    ...
    maven {
        url "https://zendesk.jfrog.io/artifactory/repo"
    }
}
```

**Add dependency in app level build.gradle**

```
dependencies {
    .....
    //zendesk
    implementation "zendesk.messaging:messaging-android:2.13.0"
}
```

**Comment by chyiiiiiiiiiiii** [comment]
Please try new version.

**Comment by JimmyTai** [comment]
Please read this doc: https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/sdks/android/known_issues/
I will add one more step for setting up proguard on README.

If u still meet the issue please re-open it or create a new issue.
