### ISSUE TITLE
uninitialize

### ISSUE THREAD

**Issue by shmink** [chyiiiiiiiiiiii/flutter_zendesk_messaging#27]
It would be great to have an `uninitialize` function. I've ran into an issue where we have subrands in our zendesk and so they each need their own channel keys. In different sections of the app a certain subrand should open but whichever subrand/section has been initialized first will be the one that remains initialized regardless of where a use maybe in the app.

**Comment by DouglasValerio** [comment]
@shmink 
Do you still need this feature?
It seems like a straightforward implementation, so I could give it a try if you're still in need of that

**Comment by shmink** [comment]
Yes please that would be amazing ❤️

**Comment by DouglasValerio** [comment]
@shmink 
Just opened the PR:
https://github.com/chyiiiiiiiiiiii/flutter_zendesk_messaging/pull/32

I encourage you to test the code on the PR on your use case, let me know if it needs some improvement

**Comment by shmink** [comment]
Apologies for the later reply.

That's awesome. Looks great to me 👍
