### ISSUE TITLE
Field to check if user is logged in

### ISSUE THREAD

**Issue by qwaiks** [chyiiiiiiiiiiii/flutter_zendesk_messaging#28]
Can we have a field to check if the is logged in.

**Comment by DouglasValerio** [comment]
@qwaiks 
Do you still need this feature?
It seems like a straight forward implementation, so I could give it a try if you're still in need of that

**Comment by DouglasValerio** [comment]
@chyiiiiiiiiiiii 
Do you think a `loggedIn` getter is a worthy addition to the package?
Personally, I think one could easily keep track of the auth state of the user in their own Flutter implementation, using the result of the `login()` method, once the auth state survives the entire lifecycle of the app.

**Comment by qwaiks** [comment]
yeah that makes sense and seems fairly easy to implement. think it would  come in  handy for the community. theres currently an error that thrown when the `logout() ` is called and the sign in fails.

**Comment by DouglasValerio** [comment]
@qwaiks 
Could you provide more info on the exception thrown in this case?
Maybe we should address this case too

**Comment by chyiiiiiiiiiiii** [comment]
Yeah, sure. The state-getter is helpful. We could have check functions.

**Comment by qwaiks** [comment]
> @qwaiks Could you provide more info on the exception thrown in this case? Maybe we should address this case too

It throws an exception with the message "Zendesk::logoutUser Failed" thats because the user is not signed in 
`_Exception (Exception: Zendesk::logoutUser failed)`
