### ISSUE TITLE
Login failure : HTTP 401 Unauthorized

### ISSUE THREAD

**Issue by Paulika855** [chyiiiiiiiiiiii/flutter_zendesk_messaging#3]
I/System.out(12879): [ZendeskMessaging] - Login failure : HTTP 401 Unauthorized
I/System.out(12879): retrofit2.HttpException: HTTP 401 Unauthorized

**Comment by tspoke** [comment]
Hi @Paulika855 

Please provide more informations. Give us your code.
How do you try to use authentication ? You need to setup a server endpoint (http) and generate a custom JWT token for use authentication. Please follow the Zendesk Documentation for this : https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/sdks/web/enabling_auth_visitors/

**Comment by Paulika855** [comment]
HI @tspoke ,

Thank you for your response.
For JWT token I just generate from  https://jwt.io/  with bellow Info:

![Screen Shot 2022-02-23 at 8 40 15 AM](https://user-images.githubusercontent.com/20048241/155248654-261fbbb2-b4a0-4dd5-bb83-4b1ed5288720.png)

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-02-23 at 08 31 12](https://user-images.githubusercontent.com/20048241/155248688-56a721d7-d96a-4b11-b75d-fd93f77bb42a.png)
