### ISSUE TITLE
Handle message on main threads

### ISSUE THREAD

**Issue by VictorUvarov** [chyiiiiiiiiiiii/flutter_zendesk_messaging#38]
I get this error when calling a platform channel method. For example calling initialize()
```
The 'zendesk_messaging' channel sent a message from native to Flutter on a non-platform thread. 
Platform channel messages must be sent on the platform thread. 
Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.
```

Flutter recommends us to send the messages on the main thread
https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading

**Comment by chyiiiiiiiiiiii** [comment]
#46 Fixed.

**Comment by Kalgros20** [comment]
Guys, this error still appears for me. Event in most recent version. 2.8.0... In ios.

I dknw it's because we are using riverpod... But it's still happening. :/

**Comment by Yiqian-karatpackaging** [comment]
this error still appears for me. Event in most recent version. 2.8.0... In ios.
