### ISSUE TITLE
iOS does not load the messages

### ISSUE THREAD

**Issue by gilsonjuniorpro** [chyiiiiiiiiiiii/flutter_zendesk_messaging#45]
I am having this problem just in iOS App, Android App works fine, does anyone have any idea how can I solve this?

Also, I am seeing this message on log

[ERROR:flutter/shell/common/shell.cc(1015)] The ‘zendesk_messaging’ channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.

Thank you

![Simulator Screenshot - iPhone 15 Pro - 2023-12-14 at 12 14 06](https://github.com/chyiiiiiiiiiiii/flutter_zendesk_messaging/assets/591951/6b4ae4ed-c9c4-4355-ba33-16c7d918093c)

**Comment by chyiiiiiiiiiiii** [comment]
#46 Fixed. Thanks.
