### ISSUE TITLE
Android Error when updated to 2.8.0 version 

### ISSUE THREAD

**Issue by harryandroiddev** [chyiiiiiiiiiiii/flutter_zendesk_messaging#48]
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > 2 issues were found when checking AAR metadata:

       1.  Dependency 'androidx.core:core-ktx:1.12.0' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.

           :app is currently compiled against android-33.

           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.3.0 is 33.

           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.

           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).

**Comment by a28115665** [comment]
@harryandroiddev 
Yes, currently 2.8.0 has this bug.
if Android Gradle plugin 7.3.0, you need use 2.7.7 version.
because this bug is dependencies _zendesk.messaging:messaging-android:2.16.0_

@chyiiiiiiiiiiii 
fix can reference
https://github.com/zendesk/zendesk_sdk_demo_apps_android/tree/main/zendesk_sdk_demo

**Comment by JimmyTai** [comment]
Please try the latest version.
