### ISSUE TITLE
Crash on logout due to TypeError when handling platform method call arguments

### ISSUE THREAD

**Issue by duyhuynh258** [chyiiiiiiiiiiii/flutter_zendesk_messaging#56]
## Summary
When logging out the user using `ZendeskMessaging.logoutUser()` on iOS, the app crashes with the following error:

## Steps to Reproduce
1. Call `ZendeskMessaging.logoutUser()` in a Flutter app running on iOS.
2. Observe the crash.

## Expected Behavior
The user should be logged out without causing a crash.

## Actual Behavior
The app crashes due to a type mismatch in the method channel arguments.

## Flutter Version
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale en-VN)

## Zendesk Messaging Version
2.8.0

## Additional Information
- The issue seems to be caused by the method channel passing a `List<Object?>` instead of a `Map<dynamic, dynamic>?`. This leads to a `TypeError` in the `_onMethodCall` function.

**Comment by chyiiiiiiiiiiii** [comment]
Thanks for the issue. Please try v2.9.0.

**Comment by duyhuynh258** [comment]
> Thanks for the issue. Please try v2.9.0.

I verified and it works. Thank for your support!
