### ISSUE TITLE
`initialize()` never resolves Future.

### ISSUE THREAD

**Issue by CodingAleCR** [chyiiiiiiiiiiii/flutter_zendesk_messaging#59]
I'm upgrading from v2.8.0 to v2.9.1.

When running the app, the method for `initialize` never resolves. It only does this if I hot reload the app. 

While debugging the code. iOS logs do show it's "initialized" but the `Future` never resolves on the Dart portion of the code.

```dart
await ZendeskMessaging.initialize(
  androidChannelKey: kAndroidChannelKey,
  iosChannelKey: kIosChannelKey,
);
```

<img width="660" alt="Screenshot 2024-10-03 at 9 47 02 AM" src="https://github.com/user-attachments/assets/ed4898bb-b81f-4934-a3b0-24ea4f5f66b1">

Android does work without problems. At this point only iOS is giving us issues.

**Comment by CodingAleCR** [comment]
Any ideas?

**Comment by JimmyTai** [comment]
Please try version 2.9.3 .
