### ISSUE TITLE
No such module 'ZendeskSDKMessaging' : flutter  3.0, ios 10

### ISSUE THREAD

**Issue by DennisMuchiri** [chyiiiiiiiiiiii/flutter_zendesk_messaging#8]
Hi @chyiiiiiiiiiiii thank you for this plugin, however I'm facing a No such module 'ZendeskSDKMessaging' issue while building for ios. Using zendesk_messaging: ^0.0.3 and xcode 13. Please help.
<img width="726" alt="Screenshot 2022-09-25 at 10 20 42" src="https://user-images.githubusercontent.com/11217100/192132799-e914b664-8c20-4038-a916-36d05611c439.png">

<img width="824" alt="Screenshot 2022-09-25 at 10 22 08" src="https://user-images.githubusercontent.com/11217100/192132781-c8c68c04-f7ac-4608-b67e-ba0605af859e.png">

**Comment by VictorUvarov** [comment]
> Hi @chyiiiiiiiiiiii thank you for this plugin, however I'm facing a No such module 'ZendeskSDKMessaging' issue while building for ios. Using zendesk_messaging: ^0.0.3 and xcode 13. Please help. <img alt="Screenshot 2022-09-25 at 10 20 42" width="726" src="https://user-images.githubusercontent.com/11217100/192132799-e914b664-8c20-4038-a916-36d05611c439.png">
> 
> <img alt="Screenshot 2022-09-25 at 10 22 08" width="824" src="https://user-images.githubusercontent.com/11217100/192132781-c8c68c04-f7ac-4608-b67e-ba0605af859e.png">

https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/sdks/ios/getting_started/#ensure-you-meet-the-minimum-supported-ios-version

**Comment by DennisMuchiri** [comment]
@VictorUvarov I did all the steps on getting started screen

**Comment by tspoke** [comment]
@DennisMuchiri Please update to v2.6.0 on pubdev released yesterday, it should fix this issue.

**Comment by DennisMuchiri** [comment]
okay @tspoke let me test
